# Server
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/venueos
spring.datasource.username=postgres
spring.datasource.password=NAJAM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=VenueOSSecretKey2026VenueOSSecretKey2026VenueOSSecretKey2026!@#
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200

# Logging
logging.level.com.venueos=DEBUG
logging.level.org.springframework.security=INFO
spring.main.allow-circular-references=true